dist: trusty
sudo: required

env:
  - TEST_SUITE=unit
  - TEST_SUITE=functional

language: php

php:
  - 7.0
  - 7.1

install:
  - 'if [ "${TEST_SUITE}" = "functional" ]; then
      . $HOME/.nvm/nvm.sh;
      nvm install stable;
      nvm use stable;
      node -v;
      npm install -g npm@latest;
      npm install -g yarn;
      npm -v;
      yarn --version;
      npm install -g bower;
      npm install -g gulp;
    fi'
  - sudo apt-get install mono-complete
  - mono --version

before_script:
  - cp .env.testing .env
  - mysql -e 'create database parkitectnexus_testing;'
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate --force;
  - 'if [ "${TEST_SUITE}" = "functional" ]; then
     yarn install;
     gulp;
    fi'

script:
  - vendor/bin/codecept run ${TEST_SUITE}